=== erikzielke/model_generator/src/main/java/com/github/erikzielke/model_generator/configuration/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="configuration" type="configurationType"/>
  <xs:complexType name="configurationType">
    <xs:sequence>
      <xs:element type="generationType" name="generation"/>
      <xs:element type="jdbcType" name="jdbc"/>
      <xs:element type="namingType" name="naming"/>
      <xs:element type="xs:string" name="excludeTable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="jdbcType">
    <xs:sequence>
      <xs:element type="xs:string" name="password"/>
      <xs:element type="xs:string" name="url"/>
      <xs:element type="xs:string" name="username"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="generationType">
    <xs:sequence>
      <xs:element type="xs:string" name="destinationDir"/>
      <xs:element type="xs:string" name="destinationPackage"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="namingType">
    <xs:sequence>
      <xs:element type="xs:string" name="tablePrefix"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== erikzielke/model_generator/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.github.com/erikzielke/model_generator/master/src/main/java/com/github/erikzielke/model_generator/configuration/config.xsd">
    <generation>
        <destinationDir>src/main/java</destinationDir>
        <destinationPackage>com.example.model.generated</destinationPackage>
    </generation>
    <jdbc>
        <password>Zwq93hhU</password>
        <url>jdbc:mysql://localhost/mybatis</url>
        <username>root</username>
    </jdbc>
    <naming>
        <tablePrefix>myprefix_</tablePrefix>
        <jndi>myprefix_</jndi>
    </naming>
    <!-- Exclude patterns are java regexps.-->
    <excludeTable>qrtz.*</excludeTable>
</configuration>
